### ISSUE TITLE
4.0.0 Crash with Better Villages, Awesome Dungeon... [Fabric/Forge]

### ISSUE THREAD

**Issue by JasonKillsUs** [jtorleonstudios/HUB-Library-Ferret#10]
libraryferret-forge-1.19.2-4.0.0 seems not compatible with bettervillage-forge-1.19.2-2.0.0.jar, getting following crash:
https://paste.centos.org/view/4d9e6caf

thanks for looking into it.

**Comment by jtorleonstudios** [comment]
Yes, you have to wait for the mods to be uploaded on Curseforge to support this new version, in 1 to 2 hours. Because it is impossible for me to upload all the mods at the same time unfortunately  (My computer is not a war machine :( it's a potato)
