### ISSUE TITLE
Request for Permission to Include mod in Modpack on Modrinth (Licensing issue)

### ISSUE THREAD

**Issue by SajmonOriginal** [jtorleonstudios/HUB-Library-Ferret#14]
Dear @jtorleonstudios,

I hope this message finds you well. I am writing to *request permission* to include your mod, "**Library Ferret - Forge**," in my modpack called "**CreateCore Reforged**," intended for the Modrinth platform. However, I have encountered **licensing issues** while attempting to publish the modpack on Modrinth due to "Library Ferret - Forge" being licensed as "*All Rights Reserved* (ARR)."

Therefore, I kindly ask if you could **grant me permission** to include "Library Ferret - Forge" in my modpack on Modrinth.

I have previously attempted to contact you through the messaging system on **CurseForge** regarding this matter. However, I have not received a response for several months. Therefore, I have resorted to reaching out to you here on **GitHub**, as I have been unable to find an alternative means of communication.

In addition to seeking permission, I would also like to propose a potential solution to address the **licensing concerns**. I suggest considering a change in the license for "Library Ferret - Forge" to a more permissive one that allows inclusion in modpacks. By adopting a license compatible with modpack distribution, such as the **GNU General Public License** or **Creative Commons Attribution-ShareAlike**, it would facilitate the seamless inclusion of your mod in modpacks and foster a vibrant modding community.

Thank you for considering my request and proposal. I appreciate your attention to this matter and *eagerly await your response*.

Best regards,

Sajmon

**Comment by jtorleonstudios** [comment]
The license is All Right Reserved. So don't re-upload on modrinth in your modpack or other

Thanks you.

**Comment by blankuserrr** [comment]
> The license is All Right Reserved. So don't re-upload/redistribute on modrinth or other websites.
> 
> Thanks you.

Does that mean use on curseforge is permitted?
