### ISSUE TITLE
[1.20.1] [Fabric] Library ferret 4.0.0 no longer works with Vanilla clients

### ISSUE THREAD

**Issue by aking4125** [jtorleonstudios/HUB-Library-Ferret#16]
Hello,

Upon updating our vanilla fabric server from 1.19.4 to 1.20.1. We updated all the Awesome dungeons mods and Library Ferret to 1.20.1.

Vanilla clients can no longer connect as it's requesting the mod to be installed on the client. This wasn't an issue with 1.19.4. We have switched to the data pack versions for now.

Any ideas?

**Comment by jtorleonstudios** [comment]
The library adds elements that are needed on both the client and server sides, You can continue to use the datapack version, but it does not include the latest feature/village added to Better Villages, you can also return to the version you were using before

In the coming months, we'll be adding decoration blocks to enhance our villages.

I'm sorry
