### ISSUE TITLE
Permission to include in modpack. 

### ISSUE THREAD

**Issue by Kasax007** [jtorleonstudios/HUB-Library-Ferret#17]
Hey jtl_elisa, for uploading a modpack on modrinth and to include any mod, I must ask for permission to include them. I would love to include your mods in my pack since it is a great way to encourage players to keep exploring new dungeons to find in different biomes. Therefore I would love to get permission to include your amazing mods in my modpack. If there is any further information you require I am happy to help!
Best regards,
Kasax

**Comment by jtorleonstudios** [comment]
dupli
