### ISSUE TITLE
Library Ferret fails to load with Forge 41.0.94 [CONFIRMED]

### ISSUE THREAD

**Issue by Gamemassa** [jtorleonstudios/HUB-Library-Ferret#2]
Minecraft version: 1.19
Forge version: 41.0.94
Library Ferret version: 2.0.0

I tried to load Minecraft with Library Ferret and Awesome Flooring and got the following error message:
![image](https://user-images.githubusercontent.com/18667108/178530930-1274fce1-5895-408b-a612-07f0fb346113.png)

I don't think Awesome Flooring itself is causing any issues, but since it relies on Library Ferret and Library Ferret is failing to load, Awesome Flooring also cannot load.

Crash Report:
[crash-2022-07-12_11.35.02-fml.txt](https://github.com/jtorleonstudios/HUB-Library-Ferret/files/9094598/crash-2022-07-12_11.35.02-fml.txt)

**Comment by TheRanker** [comment]
Please downgrade your version of library ferret. 2.0 is not used yet as the other mods are not setup to use the new Lib yet.

**Comment by jtorleonstudios** [comment]
The mod uses version 2.0.0, but it is not compiled with the forge version 41.0.94 but version 41.0.19, I will try to reproduce the error locally, the invistigation begins I keep you informed.

**Comment by jtorleonstudios** [comment]
ok I just reproduced the problem, I have to recompile the mod and the library for the forge  41.0.94 version to fix the error

While waiting for the fix, you should either delete the mod or downgrade forge to version 41.0.19.

**Comment by Gamemassa** [comment]
Just FYI, Forge got updated again. Latest is now 41.0.98

**Comment by krjencik** [comment]
ty... i need it for better villages mod...

**Comment by HellishINC** [comment]
If this wasn't closed source this could have been fixes within an hour.

**Comment by Linkink2** [comment]
It's happeing to me to and i delete the mod and reinsold it but it still did not worck
