### ISSUE TITLE
[1.16.5] Incompatible with CoroUtil/Zombie Awareness

### ISSUE THREAD

**Issue by Kaleidio** [jtorleonstudios/HUB-Library-Ferret#8]
For whatever reason, the core mod (CoroUtil) of Zombie Awareness conflicts with Library Ferret and Better Villages.

When you attempt to locate a village, then try to teleport to it, the internal server freezes as it will refuse to generate those chunks, leaving the client unsynced and unable to close.  Same issue if you attempt to walk to it manually.
You can indeed regenerate this issue with just those four mods alone, using this seed: -2887856331656635266

What methods is your library colliding with?

**Comment by Colin-J-Wood** [comment]
As it turns out it's the villages in particular that cause the issue.  Using Item Frames in nbt's causes a Zombie Awareness bug:

https://github.com/Corosauce/ZombieAwareness/issues/74
